display_name: Dart + Flutter Demo

packager: VincentZyu
packagerEmail: vincentzyu@example.com
license: MIT

priority: optional
section: x11
installed_size: 6604
essential: false
icon: ./assets/images/mahiro-pfp-VincentZyu-square.png

keywords:
  - Dart
  - Flutter
  - Demo

generic_name: Dart Flutter Demo

group: Applications/Development

startup_notify: true

