display_name: Dart + Flutter Demo

packager: VincentZyu
packagerEmail: 1830540513zyu@gmail.com
license: MIT

priority: optional
section: x11
installed_size: 6604
essential: false
icon: ./assets/images/logo-icon-favicon.png

keywords:
  - Dart
  - Flutter
  - Demo

generic_name: Dart Flutter Demo

group: Applications/Development

startup_notify: true
