display_name: Dart + Flutter Demo
package_name: dart-flutter-demo-showcase
maintainer:
  name: VincentZyu
  email: 1830540513zyu@gmail.com

priority: optional
section: x11
installed_size: 6604
essential: false
icon: ./assets/images/logo-icon-favicon.png

keywords:
  - Dart
  - Flutter
  - Demo

generic_name: Dart Flutter Demo

categories:
  - Development
  - Utility

startup_notify: true
